name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debug directory structure (optional)
      - name: Debug Directory Structure
        run: ls -R

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          if [ -d "Tests" ]; then
            pytest Tests/
          elif [ -d "tests" ]; then
            pytest tests/
          else
            echo "No test directory found!" && exit 1
          fi
