name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
<<<<<<< HEAD
        python Animal_health_classification/model/train_model.py

    - name: Run tests
      run: |
        pytest Tests/test_project.py
=======
        python model/train_model.py

    - name: Run tests
      run: |
        pytest Tests/test_project.py
>>>>>>> bc81aeb688a4485cb973e02f29f1b52f2b59a4e4
